version: '3.8'
services:
  postgres_db:
      image: postgres:15-alpine
      container_name: Postgres15Alpine
      restart: always
      environment:
        - POSTGRES_DB=parking_scheduler
        - POSTGRES_USER=lcf_dev
        - POSTGRES_PASSWORD=Abc12345~
      volumes:
        - postgres_db:/var/lib/postgresql/data
      ports:
        - '5432:5432'
volumes:
    postgres_db:
        driver: local